/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworldlib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean someLibraryMethodNew() {
        return false;
    }
}
